-- phpMyAdmin SQL Dump
-- version 5.1.1deb5ubuntu1
-- https://www.phpmyadmin.net/
--
-- Gép: localhost:3306
-- Létrehozás ideje: 2024. Már 26. 11:47
-- Kiszolgáló verziója: 8.0.36-0ubuntu0.22.04.1
-- PHP verzió: 8.1.2-1ubuntu2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `lostanimalproject`
--

--
-- A tábla adatainak kiíratása `animals`
--

INSERT INTO `animals` (`uuid`, `created_at`, `updated_at`, `userId`, `name`, `chipNumber`, `gender`, `colorId`, `description`, `image`) VALUES
('0e2ab782-3c80-43d7-856a-74924c38557c', '2024-03-26 10:12:34', '2024-03-26 10:12:34', 1, 'Púpos', '657452349565432', 1, 6, 'Donec vehicula tincidunt pulvinar. Praesent sed urna facilisis, mollis magna ut, condimentum ipsum. Etiam dapibus posuere porta. Aliquam vitae erat quis nulla ullamcorper varius condimentum pulvinar magna. Aliquam quis tincidunt quam, posuere facilisis ante. Praesent cursus leo eu sapien rutrum, non fringilla nisi tincidunt. Nulla congue finibus dictum. Nam ultricies ullamcorper orci, non tincidunt nibh hendrerit ac.', 'animal-pictures/JYXzcvjWRVLwEjaQX2hxgahtFmAXLffUoire1JNF.jpg'),
('1afaf3bd-6d61-4013-ad64-ec1efa455652', '2024-03-01 09:54:10', '2024-03-26 10:07:42', 1, 'Báró', '870247959829067', 1, 5, 'Consequatur tempora nihil sunt voluptas qui. Iusto quod aut excepturi recusandae in ratione perspiciatis eaque. Fugit dicta tempore officia provident id. Iure vero rerum consequatur. Est quas qui qui minus fuga eveniet et. Quasi sunt molestiae consequuntur et ex tenetur aut. Deleniti quis explicabo et dignissimos aspernatur nobis vel. Eveniet dicta nemo assumenda accusamus voluptatibus. Incidunt debitis nihil est natus vitae dolores voluptatum. Fuga molestias corrupti non eaque consequuntur sit. Fugit quod voluptate et sit explicabo quod expedita. Asperiores officiis dolores nihil dolorem qui fugiat nobis. Id qui reprehenderit rerum quibusdam qui. A fugiat repellendus tenetur alias. Enim eligendi tempora cum porro dolorem. Sint ab similique debitis ducimus ad. Accusantium incidunt est sit officiis ex officiis vel nesciunt.', 'animal-pictures/0FqdPIEFysZcElkk6bCa8azC8rufOgWdfog9BG1h.jpg'),
('1b6cb5b8-2d51-4e79-8bd6-adfd32a8a56a', '2023-01-01 09:54:10', '2024-03-26 09:54:10', 1, 'Zeus', '817695504277257', 1, 5, 'Et nisi dolorem id maxime. Modi mollitia provident molestiae explicabo fugit cum voluptas. Fuga provident sit sunt autem ipsum quidem accusantium. Occaecati qui inventore aut rerum tempora. Inventore delectus ratione dolorum optio provident qui consequatur. Et ipsum voluptates cum corrupti quibusdam autem. Quaerat temporibus voluptatem sapiente dolores id aut tempore officia. Sapiente possimus deserunt hic eaque facilis quasi laborum. Qui ad incidunt nam enim. Libero dolores quibusdam ut tempora non quod doloribus. In eveniet magnam voluptatem beatae non ipsam enim iste. Doloribus cum et totam fugiat. Ipsum nihil necessitatibus non adipisci facilis dicta modi. Suscipit et est voluptatem molestiae qui. Magni repellendus eligendi dicta nostrum nostrum iusto tempore. Sit sint ex impedit. Natus quia itaque est et eum. Nemo recusandae recusandae ut repellat dolorum. Consequuntur labore repudiandae consequatur ut eos laudantium. Unde quia recusandae et vel.', 'animal-pictures/0YvP1g6mfRz0vzI2xktaGe0ksDb3INiyR2BlIps6.jpg'),
('28db360c-d533-4a60-a0db-d041d59917ce', '2024-02-26 19:54:10', '2024-03-26 10:06:54', 1, 'Felix', NULL, 1, 1, 'Rerum dolor fugit ut illum voluptas sunt dolores sequi. Corrupti incidunt consequatur deserunt delectus. Est voluptatem quibusdam tempore eveniet iusto. Qui natus unde occaecati. Quo sunt non fuga. Maxime voluptatem tenetur et exercitationem sit et omnis. Quia qui maiores quia consequatur libero quam debitis. Ratione soluta quibusdam illum nobis vero aut pariatur. Voluptates reprehenderit quis sequi reprehenderit sit tenetur placeat. Qui accusamus doloremque est nobis vel corporis qui. Corporis vero sed autem sunt. Necessitatibus deleniti mollitia nam minus facilis tempora ea illum. Consequatur saepe suscipit sit culpa ut. Natus dolore vel rerum quo. Consequatur temporibus voluptatum harum dolorum excepturi quia natus consequatur. Tempore quas veniam quia corporis consequuntur dolorem sint. Nobis praesentium sed minus commodi fugit aut facere. Quia et aut incidunt iure neque et modi.', 'animal-pictures/1EpnWhi3CAKCpMaiWOU1HxgaSvdVJ9BQpIfTsRzO.jpg'),
('29350024-28d9-473e-a7fe-6b3d2f86a0ed', '2024-01-26 07:54:10', '2024-03-26 10:07:00', 1, 'Bogyó', '530597102792751', 0, 1, 'Autem quasi tempore delectus mollitia ex vero. Quia libero ut quia molestiae. Rem sapiente doloribus repellat magnam voluptas laborum et. Nulla sunt nisi error eos porro laborum. Animi quam laboriosam a earum possimus. In autem ipsam facilis explicabo quia. Ex numquam omnis voluptatibus magnam aut sed. Voluptas et porro eum dolores voluptas. Voluptate quibusdam quia veritatis omnis. Illum iste voluptas dolores porro illum dolores. Molestias quod non fugiat labore distinctio velit. Consequuntur maxime enim aut. Libero voluptas vel dolorem quia dignissimos. Enim ut aut et asperiores enim. In illum rerum rerum aut dolorum. Sit possimus sunt est illum accusamus repellendus explicabo. Porro ut dignissimos aliquam omnis id iure placeat. Aspernatur facilis tempora eaque inventore. Veritatis eius neque ipsam repudiandae. Eligendi harum doloremque possimus officiis possimus molestiae. Quia aut est sed nihil. Ad qui qui est exercitationem nam repudiandae vero numquam.', 'animal-pictures/7BowCIqXZYs0UxTjAL3HDjl2JJQ7d5sAYVInfKpa.jpg'),
('40058079-3da2-4f22-919e-28d15bdb4a26', '2021-12-08 09:54:10', '2024-03-26 09:54:10', 1, 'Mogyoró', '795159716177246', 0, 1, 'Cupiditate magni officia voluptatem doloribus. Nobis voluptas non minus et suscipit unde itaque. Non vero voluptatum explicabo possimus. At qui veniam veritatis et omnis. Nesciunt consequatur quia architecto totam id quas. Et dolorum quos autem quis. Aliquam eos quas dignissimos eius veniam distinctio assumenda. Natus veritatis enim ut similique quo aut. Et molestiae voluptatum tempora. Iusto magni ipsa adipisci voluptatem voluptas laudantium. Minima ut iure quasi nam voluptatem. Enim ratione excepturi aut voluptas ut harum. Et sed dicta ut atque. Sed enim dolor perspiciatis et et sint molestias. Dignissimos sunt qui repellendus. Dolores dignissimos fugiat at et sint quam sint. Corrupti ducimus accusantium eligendi corporis qui sit. Porro minima doloribus nemo quia natus veritatis. Facere qui totam eligendi aut.', 'animal-pictures/67pFtv0jj3oZ9J00vpjx41lKZMgyOeURVtnOtVsQ.jpg'),
('596d49b0-3bdc-4cf6-8bf3-106bef3a68d1', '2024-03-26 09:54:10', '2024-03-26 10:07:09', 1, 'Max', NULL, 1, 1, 'Maiores neque ut qui occaecati est reprehenderit qui et. Officiis laborum officiis qui autem aliquam sed quos asperiores. Quo voluptatibus in dolorum. Qui reprehenderit voluptates eveniet repudiandae molestiae provident eligendi. Quibusdam quam quam nostrum qui voluptatem. Est distinctio maiores magnam ipsam voluptatem quam doloribus. Omnis corrupti eaque et dolorem magnam soluta voluptas. Fugit eum et ipsa qui porro libero id. Consequatur reprehenderit repellat ratione aliquid hic. Libero quos consectetur rem ea doloribus labore. Iure tenetur voluptatibus voluptas minima pariatur. Fugit cum neque aut ut natus eum. Deleniti minus rerum id reiciendis cumque quae. Dolor blanditiis quisquam dolore molestiae voluptatum laborum quo. Delectus nobis harum inventore ipsa id nulla. Ratione sunt sapiente exercitationem quis eligendi debitis velit. Eos amet rerum sit velit quam quisquam. Doloribus et reprehenderit dolor qui nobis ea voluptas totam.', 'animal-pictures/daztDyxGvjYp3W26BsVJekAL6UrTw3LO68aSBkMi.jpg'),
('6170009d-c5ba-4d5d-8b16-87868384d3a7', '2024-03-24 09:54:10', '2024-03-26 10:07:18', 1, 'Bodri', '429725231173358', 1, 3, 'Id quibusdam accusantium suscipit tenetur quia. Aut qui quod nemo sunt. Ad sequi quos atque molestias optio. Hic eius dolorem et ratione et atque. Vel soluta et modi assumenda suscipit voluptas excepturi. Est temporibus qui maxime molestiae. Illum rerum est ab ut. Vel asperiores est fugit aspernatur fugit libero. Qui cumque praesentium sunt modi quia deleniti. Totam quod et quam veritatis et. Modi rerum et aut quia sit. Veniam et est eligendi dolores. Qui quis consequatur omnis esse quia at. Reiciendis nulla et officia molestiae voluptate voluptatem molestiae animi. Suscipit tempore id nobis quas in tempore et. Velit nihil voluptatem atque voluptatem voluptatem. Quia est modi consectetur libero omnis nihil nulla eveniet. Nam ipsam cum perspiciatis quia consequatur occaecati quas. Commodi beatae deserunt officia quia adipisci cum. Adipisci fugiat odio neque voluptas. Ut ut voluptatibus in veniam molestiae quisquam aut. Et tempora voluptatem et omnis nobis.', 'animal-pictures/dgJQuUIFDKSiGHQ0gkRorZGaorjAzn2RaOvST2Im.jpg'),
('71575ec0-66f0-428c-877f-120d4d67b9c2', '2024-02-09 13:14:10', '2024-03-26 10:07:36', 1, 'Csibész', '429773858829212', 1, 4, 'Illum molestiae non magnam sunt id. Dolorem vel autem similique sit. Deleniti quo amet molestias. Impedit veritatis nemo nulla libero ea perferendis. Occaecati amet et dolorum aut voluptas et ex. Ut molestias explicabo iusto voluptatem dolorem dolorem. Quos delectus qui sit tenetur nesciunt deserunt. Sed repellendus nesciunt ab ullam. Ut quis qui commodi optio nihil saepe dicta officiis. Quis ex eius eligendi eos. Id sapiente non laborum culpa soluta accusantium velit. Fugiat libero earum quis molestias. Laborum aspernatur tenetur omnis nihil sapiente ut. Voluptas impedit vero eum ullam officia fugiat in. Sit omnis repudiandae est amet quas inventore. Deleniti et non quidem. Corrupti iure architecto ea corrupti. Explicabo sed rem in temporibus voluptas temporibus asperiores optio. Sapiente voluptas voluptatem quae culpa quaerat rerum et natus. Quas similique autem et expedita facere molestias architecto. Aperiam animi voluptates est fuga. Itaque accusamus assumenda deleniti.', 'animal-pictures/Dlusxav0GdAae8nXknGyBB9g4uDtJBluYztyvePJ.jpg'),
('ac7a8259-75e1-44ad-804c-438f1097fba6', '2021-12-04 10:54:10', '2024-03-26 10:07:26', 1, 'Csillag', '701661110172036', 0, 3, 'Cumque ex aliquam sint quo placeat eos. Eligendi velit aperiam saepe consequatur ducimus. Repellendus in iusto est quia dolores qui praesentium. Nulla perspiciatis aperiam libero id aut illum non voluptatem. Accusamus magnam debitis minima labore. Quam vel repellat quidem. Est quod officiis fugiat ipsum similique nemo. Aperiam qui saepe et doloribus aperiam consequatur. Rem quam adipisci corrupti temporibus vel. Sint vitae error rerum quod sunt dolores eius similique. Inventore fuga eos rerum quas animi. Praesentium nemo distinctio quidem. Facilis qui accusamus ratione neque alias omnis repudiandae. Aperiam tenetur animi cupiditate consequuntur. Sunt placeat quasi minus sequi. Beatae officiis odio ab adipisci velit qui voluptatum. Esse consequatur minus incidunt facilis ipsum sed. Officiis nihil ut eaque in molestias amet. Ut asperiores aut iusto eligendi aut possimus. Laboriosam et reiciendis eligendi in velit est non.', 'animal-pictures/eGK7JhhkdqPSGUr8zXA5142cFxEqWCnete2nFopH.jpg'),
('b084b825-ce8e-43bc-97f7-3f8196ed4c6a', '2023-04-26 05:54:10', '2024-03-26 10:06:24', 2, 'Pajti', '061503611008918', 1, 4, 'Voluptas ut quis est et eum non expedita. Sed a perspiciatis facere enim distinctio ad. Quibusdam id magnam maxime quae. Ea consequatur quis sint. Rerum sint saepe accusantium. Voluptatem aut facere aut magni quia debitis omnis. Nobis odit asperiores nemo. Quod itaque voluptatem eius autem iusto natus. Sed sit doloremque aut dolore. Consequuntur itaque rerum inventore provident et. Error perspiciatis eligendi accusantium laborum mollitia est. Quis molestiae quo ducimus veritatis voluptatem nostrum est. Voluptate delectus voluptas illum a. Amet ab hic numquam recusandae qui eos blanditiis. Expedita est non accusantium qui aut. Inventore dolorem aut corporis. Voluptatum aut quis ut rem doloribus adipisci dolor est. Est sit quae eligendi architecto id distinctio. Illum nulla quae rerum consequatur eum. Sunt velit molestiae consequuntur maiores perspiciatis.', 'animal-pictures/fsDQ9ZA0TFIK5kzTe9m1FYkVCatFGVGjWrgFYf2J.jpg'),
('b4c1c7e6-648d-4d39-a4b4-5b361812a478', '2024-03-25 11:54:10', '2024-03-26 10:06:49', 2, 'Tappancs', '240814103670498', 1, 4, 'Reprehenderit sapiente consequuntur qui. Ea provident quia sint temporibus sit dolore ut. Et eaque veniam atque placeat eveniet. Cupiditate cum esse sit aut perferendis atque. Laborum asperiores alias mollitia omnis perspiciatis voluptatem sit. Excepturi quo dignissimos quas inventore minima consequatur. Officia ea minima exercitationem. Eos ab accusamus saepe. Fugiat temporibus nulla necessitatibus facere. Sed cum qui eos eum consequatur. Rerum aliquam debitis velit sint fugit sit ut voluptatem. Et nemo eligendi est. Repellendus vel autem rerum facilis quod neque. Voluptatem a commodi ut voluptatum. Laboriosam consequuntur quo vel possimus. Voluptatem nam quidem autem deserunt et qui facilis. Rerum ut voluptates accusantium mollitia. Quos natus mollitia at aut sed non eos. Voluptatem iusto laboriosam modi est vitae nostrum. Iste ea modi iste culpa eaque non.', 'animal-pictures/FWuhxdZTaabbnQN8zqOWuxX90SEGWegJ93i73i3B.jpg'),
('b68ebdd0-ce79-409f-b92b-aa4e906d6b7a', '2024-01-23 23:54:10', '2024-03-26 10:06:56', 2, 'Huncut', '805558335436164', 1, 5, 'Rerum adipisci quae voluptas sed. Porro distinctio ullam cumque doloremque voluptatum nihil eos. Esse aut doloremque eveniet. Incidunt excepturi magnam at impedit. Repudiandae minima facilis et quasi dignissimos. Modi veritatis eveniet nam voluptate saepe. Ad est magni nesciunt optio debitis ea. Molestiae labore voluptatum consequatur error. Eligendi quis nihil consequatur error reiciendis libero minus. Est nihil qui nisi occaecati sed dolore. Omnis est fuga quia ut sunt vel sunt. Voluptatum quia enim quam id pariatur. Aut amet cupiditate aut eligendi. Officia quia accusamus enim tenetur et nulla. Iure est omnis natus saepe dolorum voluptas quas. In nemo aut ut fuga autem vel. Architecto et soluta est est voluptatem. Alias nisi atque sequi et illum reiciendis expedita et. Sapiente sint nobis quas labore voluptas. Nesciunt deserunt qui quo consequatur. Quis et iure ipsum similique cumque ab nisi ea.', 'animal-pictures/h1QVDhOA2kUfe94KCmmbRouHy4EBorW3HEcKoRc1.jpg'),
('ba2019a3-5da8-4efb-bbe5-86017b61550c', '2023-02-26 15:54:10', '2024-03-26 10:07:02', 2, 'Foltos', '267930753721642', 1, 7, 'Quia quaerat eligendi temporibus expedita voluptatem. Vel vero et sit tenetur ducimus autem consequuntur. Perferendis numquam nesciunt quis. Vero qui autem ut in. Impedit perferendis incidunt in praesentium. Quia error quia quam et. Quos iure impedit aut consequuntur quis cum veritatis aut. Provident explicabo odio omnis provident. Animi qui temporibus officia doloremque sunt ipsa natus. Pariatur est hic autem cum consequatur. In fugit fuga et. Blanditiis ullam vitae rem aut voluptatem culpa non. Perspiciatis tempora est sit velit earum. Perspiciatis qui mollitia enim cumque pariatur sapiente fugit. Officiis quidem voluptas saepe minus. Excepturi numquam iusto quidem quo voluptatibus consectetur. Officia exercitationem animi fugit. Neque libero laudantium non quo sunt quia. Aut dolor omnis rerum voluptatibus quibusdam soluta. Omnis repellendus delectus quaerat dolore et et quis.', 'animal-pictures/hhKAtYKEb5A0ERTTUMK50rBIEfhrGHDQjRpYsxvc.jpg'),
('caed61eb-9059-4b52-b15d-b8dd683a4cac', '2023-05-26 21:54:10', '2024-03-26 10:07:09', 2, 'Csavargó', NULL, 1, 1, 'Aperiam hic sunt ut et. Qui vitae et voluptas facere est. Omnis possimus et sed ut. Voluptatum qui modi ad voluptatem. Ullam et ea nihil error assumenda nulla accusamus ipsa. Sapiente harum perspiciatis consequuntur occaecati ut. Odit rerum hic et blanditiis ipsa numquam. Natus est saepe ut perspiciatis voluptatum quis optio. Architecto officia recusandae voluptatibus commodi harum eum voluptate omnis. Quidem odio laudantium qui vero quo similique culpa. Quod et harum ut adipisci. Sed enim in eaque aut ducimus. Iste quia quas et. Harum quo est sunt iure qui totam hic. Ut sed architecto corporis veritatis. Accusantium est perferendis sit explicabo nisi neque. Et praesentium similique repellendus et. Voluptate quis ea corrupti quo perspiciatis veritatis. Maxime libero suscipit quidem consequuntur saepe dolor autem. Dolore nihil ut et at et ipsam. Accusamus ipsum quos veniam minima non. Saepe cum aperiam doloribus itaque quia expedita expedita.', 'animal-pictures/Lr1elZlwRIh9ptz7WVruE910e4CZwRYAqncLiveL.jpg'),
('ce206269-19bd-491f-b3fb-877e07e6a357', '2024-01-30 22:54:10', '2024-03-26 10:07:33', 2, 'Bodza', '785321145037654', 0, 4, 'Rerum eius distinctio amet delectus ipsam illum. Sed laudantium enim eum sit exercitationem nemo delectus. Quae quod necessitatibus dolores iste culpa officiis voluptatem repudiandae. Non consequatur eligendi dolorem quod facere perspiciatis consequatur. Dolores consequatur dolor ipsa molestiae. Esse dolore rerum voluptas similique provident consectetur ratione. Molestias natus quia aut architecto dolore. Eos voluptate non pariatur ducimus odio a eius nostrum. Sequi reiciendis aliquam incidunt cupiditate nihil in. Voluptate eveniet quisquam odio quia iste rem. Iste sed recusandae assumenda quia ea laboriosam. Odio blanditiis repellat quibusdam ut id nobis. Rerum dolor enim harum nostrum. Et harum ut necessitatibus culpa. Numquam qui iusto non dolorem culpa. Distinctio culpa dolorum consequatur incidunt ut sint. Hic doloremque voluptatem consequatur iure eius iste ut.', 'animal-pictures/o2i4m2SP7S2st9AzADyZQRDdhf0cLuhF7AVuOaUF.jpg'),
('d4d57c99-fa57-468e-93c5-9d845942cb57', '2022-03-01 14:54:10', '2024-03-26 10:07:39', 2, 'Pötyi', '204016329586781', 0, 7, 'Minus quasi quibusdam corporis vel voluptatibus porro qui. Laboriosam aspernatur earum atque aut. Praesentium quidem aut voluptatem. Blanditiis sint quibusdam similique quasi sunt. Enim quia reiciendis soluta pariatur ut. Aliquam maxime sit eaque velit. Facere ea molestiae esse ab vero sint. Tempora consectetur exercitationem voluptate similique in. Id quasi nesciunt quo corporis ea. Rerum esse quas iure odio doloribus. Perferendis corrupti error dolor facilis quasi modi. Aut et quisquam similique alias velit. Quo omnis voluptas in ea quis. Ea vel nulla aut necessitatibus quis possimus. Voluptatum rem aut sit ab incidunt. Illum sapiente ipsa reprehenderit minus. Ea placeat est aperiam et dolor soluta. Quia impedit officiis rerum atque. Impedit culpa ea in et aperiam. Voluptas quo ex provident sed illo dolores eligendi. Praesentium doloribus tenetur est voluptatum debitis et.', 'animal-pictures/pN44RuJ8bMjBsw9DDnHtrRK43yiW6FLEFwx9KBEy.jpg'),
('dbaf8586-888c-4156-b0da-11bb767c233c', '2024-01-01 09:54:10', '2024-03-26 10:07:45', 2, 'Gombóc', '981939413177183', 0, 3, 'Quam sint molestiae quis consequatur. Et et minus laborum non inventore. Beatae quis distinctio fugit qui praesentium et. Aut sit dolore tempore cumque saepe distinctio sint. Nulla dignissimos dolor non minus quo. Sed totam repudiandae non praesentium iure impedit quo. Magnam ad accusamus corrupti alias et. Modi ducimus sed aut quod itaque. Non porro in eaque sit et est ex. Aut voluptatibus nulla facere et alias molestias impedit. Qui dignissimos dolor iure aut nulla est. Dolor voluptatem ab nihil tenetur. Suscipit culpa molestiae sequi enim ut ut. Accusantium et distinctio est modi temporibus. Est quia omnis vel vero. Voluptatem dolorem ut eveniet et ipsa. Eos qui modi quasi sint soluta aut. Voluptatem rerum ipsam ratione. Ut placeat cumque quae aut velit eum. Non deserunt odio qui est. Mollitia non ipsa sit et quasi aut quasi qui. Libero itaque saepe sint modi cumque. Aut laboriosam facere quis autem esse nobis qui.', 'animal-pictures/RkeK8DJiZOJ6vhbdUQn9mp4FjqSEQiBsUkLS6XlJ.jpg'),
('e247de8d-04e3-48b9-ab94-92ef63f1f9f5', '2022-03-20 09:54:10', '2024-03-26 10:07:57', 2, 'Lola', '323968348273634', 0, 4, 'Ut qui laboriosam ut perferendis numquam qui. Voluptatum illo quae enim adipisci reprehenderit omnis. Nisi accusamus nihil eos atque est. Similique repellendus ut dicta et impedit. Accusantium et natus repellat porro. Rerum quas ratione vero sunt qui tempore. Velit iste maxime voluptatem nihil est suscipit et. Est dolore et in natus. Dolores qui ipsum quibusdam quia. Ex optio cupiditate sit sed eum fugiat. Ducimus et harum omnis quis eligendi. Sit et qui magni ipsam. Ad aliquid ad est sit aut. Velit exercitationem magnam sapiente enim aut qui ipsam eligendi. Omnis voluptates autem eos molestiae totam et optio. Et repudiandae assumenda dolore cum qui ut. Nesciunt repudiandae molestiae atque magnam consequatur est consequuntur. Fugit aspernatur et soluta officiis amet. Sunt voluptas sequi labore minus. Illo id culpa atque tempore fugit non expedita. Quidem ducimus beatae distinctio voluptatibus.', 'animal-pictures/S3yeBLyrUJ4UtWYwWbo7FdavjZWfhcSkMf95TyBU.jpg'),
('e34cfd02-f515-45de-bb27-f642b224ff73', '2024-03-20 14:00:00', '2024-03-26 10:08:08', 2, 'Málna', '943129956515906', 0, 5, 'Et animi ipsum accusamus illum voluptas. Dolores reiciendis officia ea voluptatum sit assumenda laudantium. Quos dolores nihil quis. Ut excepturi est dolor blanditiis. Iusto aut repellendus numquam sit. Omnis architecto ut impedit impedit. Ullam delectus sunt magnam. Rerum nemo aliquid occaecati voluptatem atque voluptates maxime. Repellat odit magnam placeat et. Hic accusamus est libero omnis delectus. Dolorum enim numquam tempore nihil. Minima delectus at molestiae cupiditate dolor. Eligendi repellendus consectetur nulla fugiat ipsa delectus. Consectetur corrupti et error nihil et. Ut nihil laborum amet quo. Pariatur dolor ut non. Quia enim modi id sint. Explicabo nihil ut quia delectus omnis sequi. Quas accusamus architecto laboriosam eum beatae minus. Et sunt recusandae ratione dolorem sequi. Et velit aut voluptatibus quia accusamus error. Dicta porro dicta et aut ipsam sit.', 'animal-pictures/Uolhj48qeajEQoDCLtbwMuqYFz088hwbidq9wNhd.jpg'),
('ef56492b-d00e-48a7-a89b-ef6c506067fc', '2024-02-29 16:54:10', '2024-03-26 10:08:14', 2, 'Csillag', NULL, 0, 2, 'Sit dolor est neque aut quaerat dolor. Ab est minima facilis. Eaque sapiente quo consequatur. Rem et et et sit quo ut enim. Ut repellendus inventore nostrum dicta. Reiciendis delectus qui quia omnis nihil optio. Fugiat minima ex sed provident. Illum ad odio nostrum facilis modi. Autem beatae aut sunt et et. Saepe dolorum dignissimos error labore dolorem ex ea modi. Est inventore beatae debitis similique. Ea ut voluptas reprehenderit. Provident architecto maxime non qui qui labore. Ut quidem aut ducimus velit hic fugit. Nihil vel quia delectus quam nobis qui explicabo. Laborum dolores quia consequatur et aliquid eos. Fuga et temporibus facere. Eius est repellat porro cupiditate earum explicabo. Fuga ex repudiandae repellat. Qui non velit magnam rerum. Non totam magnam qui et maiores pariatur. Numquam saepe et libero ullam omnis labore. Assumenda omnis quos officiis quo nihil nulla dolorem odit. Deserunt magni minus asperiores quia tempora adipisci dolorem.', 'animal-pictures/vfPGAa1YR7DhEN4pnz6uE6phYrcRNbnRvgCDxPLU.jpg'),
('f28afb37-be3e-44d3-9296-9464a2d22b72', '2024-03-26 09:54:10', '2024-03-26 10:08:25', 2, 'Penge', NULL, 1, 3, 'Pariatur quae nesciunt voluptatibus eum est. Enim architecto voluptas sunt dolor. Quia dolore et quia animi voluptate. Qui magni dolores a iste dolorum omnis ut. Quisquam enim excepturi dolores tempore consequatur qui. Enim hic aut itaque perferendis ut labore. Voluptatem est vero et blanditiis. Voluptatum quisquam dolorum quasi nobis in sed unde. Ipsam quisquam veniam maxime et et. Possimus aliquam et iusto nobis rerum laborum iure odit. Ea necessitatibus dolore neque reprehenderit reprehenderit qui. Qui dolorum ipsam dolores fugit consectetur. Architecto ad inventore temporibus aut hic sit. Molestiae dolorem atque aut expedita. Omnis quaerat in non vitae. Omnis ut sit quam modi laboriosam quis qui. Aut praesentium soluta quaerat natus ut aliquid. Reprehenderit repellat rerum pariatur. Odio sit autem et cumque repudiandae asperiores.', 'animal-pictures/WxIXJN4qM0fXTjYv0smDGy2CyJzSF71dEMoXaUW1.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
